services:
  backend:
    container_name: django-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
    command: python manage.py runserver 0.0.0.0:8000